version: "3.9"

services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: warhammer-api
    ports:
      - "8000:8000"
    networks:
      - warhammer-network
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: warhammer-front
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - warhammer-network
networks:
  warhammer-network:
    driver: bridge
